### ISSUE TITLE
Please add credits (Majo.exe)

### ISSUE THREAD

**Issue by IgorKowalczyk** [deepsarda/Aeona-Discord#5]
Hello, this code is actually [Majo.exe](https://github.com/IgorKowalczyk/majo.exe). The code has been copied, **the credits files have been deleted or modified**. Please create a readme file with information that this project is a fork of [@igorkowalczyk/majo.exe](https://github.com/IgorKowalczyk/majo.exe)

### Files with credits
```diff
- readme.md (REMOVED)
- license.md (REMOVED)
+ .gitignore (UNMODIFIED)
+ .github/workflows/format.yml (UNMODIFIED)
+ Procfile (UNMODIFIED)
- config/main_config.js (MODIFIED)
... and many other files
```

### How do I add credits?
- [Add ascii art to the index.js file as in the original bot](https://github.com/IgorKowalczyk/majo.exe/blob/master/index.js#L1-L11)
- [Add license file as in the original bot](https://github.com/IgorKowalczyk/majo.exe/blob/master/license.md)
- Add information in the readme including a link to the original project

**Comment by deepsarda** [comment]
Okay
